// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vocabulary.API.Models.Entities;

#nullable disable

namespace Vocabulary.API.Migrations
{
    [DbContext(typeof(VocabularyDBContext))]
    [Migration("20230112185746_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CourseUser", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CourseId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("CourseUsers", (string)null);
                });

            modelBuilder.Entity("Vocabulary.API.Models.Entities.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Cards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            CreatedDate = new DateTime(2023, 1, 12, 21, 57, 45, 855, DateTimeKind.Local).AddTicks(4945),
                            IsDelete = false,
                            Title = "A1",
                            UpdatedDate = new DateTime(2023, 1, 12, 21, 57, 45, 855, DateTimeKind.Local).AddTicks(4945)
                        });
                });

            modelBuilder.Entity("Vocabulary.API.Models.Entities.CardSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CardId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FalseCount")
                        .HasColumnType("int");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFinish")
                        .HasColumnType("bit");

                    b.Property<double?>("Scor")
                        .HasColumnType("float");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrueCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("UserId");

                    b.ToTable("CardSession", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CardId = 1,
                            CreatedDate = new DateTime(2023, 1, 12, 21, 57, 45, 855, DateTimeKind.Local).AddTicks(5001),
                            EndDate = new DateTime(2023, 1, 12, 21, 58, 45, 855, DateTimeKind.Local).AddTicks(5002),
                            FalseCount = 2,
                            IsDelete = false,
                            IsFinish = true,
                            StartDate = new DateTime(2023, 1, 12, 21, 57, 45, 855, DateTimeKind.Local).AddTicks(5009),
                            TrueCount = 2,
                            UpdatedDate = new DateTime(2023, 1, 12, 21, 57, 45, 855, DateTimeKind.Local).AddTicks(5001),
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Vocabulary.API.Models.Entities.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 1, 12, 21, 57, 45, 855, DateTimeKind.Local).AddTicks(5026),
                            Description = "İngilizce'nin ilham verici öğretim metodu ve kapsamlı kurs Bölüm 1 karşınızda. Kendini İngilizce tanıt, İngiltere'yi tanı, ve insanları gülümsetmek için onlarca İngilizce günlük ifadeyi öğren. Günlük konuşma İngilizcesini öğrenmek artık çok kolay.",
                            IsDelete = false,
                            Title = "İngilizce 1",
                            UpdatedDate = new DateTime(2023, 1, 12, 21, 57, 45, 855, DateTimeKind.Local).AddTicks(5026),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 1, 12, 21, 57, 45, 855, DateTimeKind.Local).AddTicks(5028),
                            Description = "Kendini İngilizce tanıt, Amerika'yı tanı, ve insanları gülümsetmek için onlarca İngilizce günlük ifadeyi öğren. Amerikan İngilizcesini öğrenmek artık çok kolay.",
                            IsDelete = false,
                            Title = "Amerikan İngilizcesi 1",
                            UpdatedDate = new DateTime(2023, 1, 12, 21, 57, 45, 855, DateTimeKind.Local).AddTicks(5029),
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 1, 12, 21, 57, 45, 855, DateTimeKind.Local).AddTicks(5031),
                            Description = "Kendini Almanca tanıt, Almanya'yı tanı, ve insanları gülümsetmek için onlarca Almanca günlük ifadeyi öğren. Günlük konuşma Almancasını öğrenmek artık çok kolay.",
                            IsDelete = false,
                            Title = "Almanca 1",
                            UpdatedDate = new DateTime(2023, 1, 12, 21, 57, 45, 855, DateTimeKind.Local).AddTicks(5031),
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 1, 12, 21, 57, 45, 855, DateTimeKind.Local).AddTicks(5033),
                            Description = "",
                            IsDelete = false,
                            Title = "En Çok Kullanılan 3000 Kelime",
                            UpdatedDate = new DateTime(2023, 1, 12, 21, 57, 45, 855, DateTimeKind.Local).AddTicks(5033),
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2023, 1, 12, 21, 57, 45, 855, DateTimeKind.Local).AddTicks(5035),
                            Description = " Bu kurs temel kelimeler ve ifadeler ile hemen İngilizce konuşabilmeye başlayabilmeniz için tasarlanmıştır.",
                            IsDelete = false,
                            Title = "İngilizce'yi Söküyoruz!",
                            UpdatedDate = new DateTime(2023, 1, 12, 21, 57, 45, 855, DateTimeKind.Local).AddTicks(5036),
                            UserId = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2023, 1, 12, 21, 57, 45, 855, DateTimeKind.Local).AddTicks(5037),
                            Description = "İngilizce'de yaygın olarak kullanılan 250 pratik. Sık kullanılan Sorular, Durumlar v.b",
                            IsDelete = false,
                            Title = "250 İngilizce Pratik",
                            UpdatedDate = new DateTime(2023, 1, 12, 21, 57, 45, 855, DateTimeKind.Local).AddTicks(5038),
                            UserId = 1
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2023, 1, 12, 21, 57, 45, 855, DateTimeKind.Local).AddTicks(5040),
                            Description = "Phrasal Verbs Türkçe Anlamları",
                            IsDelete = false,
                            Title = "Phrasal Verbs Türkçe",
                            UpdatedDate = new DateTime(2023, 1, 12, 21, 57, 45, 855, DateTimeKind.Local).AddTicks(5040),
                            UserId = 1
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2023, 1, 12, 21, 57, 45, 855, DateTimeKind.Local).AddTicks(5042),
                            Description = "",
                            IsDelete = false,
                            Title = "YDS Çıkmış Kelimeler",
                            UpdatedDate = new DateTime(2023, 1, 12, 21, 57, 45, 855, DateTimeKind.Local).AddTicks(5042),
                            UserId = 1
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2023, 1, 12, 21, 57, 45, 855, DateTimeKind.Local).AddTicks(5044),
                            Description = "Oxford eğitmenleri tarafından hazırlanan, İngilizce'de en çok kullanılan 3000 kelime",
                            IsDelete = false,
                            Title = "The Oxford 3000 (İngilizce - Türkçe)",
                            UpdatedDate = new DateTime(2023, 1, 12, 21, 57, 45, 855, DateTimeKind.Local).AddTicks(5044),
                            UserId = 1
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2023, 1, 12, 21, 57, 45, 855, DateTimeKind.Local).AddTicks(5047),
                            Description = "Amerikan Kültür ve Dil Kursu içi Hazırlanmış Portfolyosundaki Kelimeleri İçeren Mükemmel Bir Kurs",
                            IsDelete = false,
                            Title = "İngilizcedeki En Önemli 1250 Kelime",
                            UpdatedDate = new DateTime(2023, 1, 12, 21, 57, 45, 855, DateTimeKind.Local).AddTicks(5048),
                            UserId = 1
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2023, 1, 12, 21, 57, 45, 855, DateTimeKind.Local).AddTicks(5050),
                            Description = "Advanced English for speakers of Turkish: this course consists of a collection of useful and idiomatic phrases or sentences to help you improve your pronunciation as well as develop fluency when using complex structures.",
                            IsDelete = false,
                            Title = "Gelişmiş ingilizce - Advanced English",
                            UpdatedDate = new DateTime(2023, 1, 12, 21, 57, 45, 855, DateTimeKind.Local).AddTicks(5050),
                            UserId = 1
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2023, 1, 12, 21, 57, 45, 855, DateTimeKind.Local).AddTicks(5052),
                            Description = "Temel Seviyede İngilizce Öğrenme Kursu",
                            IsDelete = false,
                            Title = "Temel İngilizce",
                            UpdatedDate = new DateTime(2023, 1, 12, 21, 57, 45, 855, DateTimeKind.Local).AddTicks(5052),
                            UserId = 1
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2023, 1, 12, 21, 57, 45, 855, DateTimeKind.Local).AddTicks(5054),
                            Description = "",
                            IsDelete = false,
                            Title = "İngilizce İlk 1000 Kelime",
                            UpdatedDate = new DateTime(2023, 1, 12, 21, 57, 45, 855, DateTimeKind.Local).AddTicks(5054),
                            UserId = 1
                        },
                        new
                        {
                            Id = 14,
                            CreatedDate = new DateTime(2023, 1, 12, 21, 57, 45, 855, DateTimeKind.Local).AddTicks(5056),
                            Description = "A1, A2 seviyeleri için temel kelimeler",
                            IsDelete = false,
                            Title = "İngilizce Temel Kelimeler",
                            UpdatedDate = new DateTime(2023, 1, 12, 21, 57, 45, 855, DateTimeKind.Local).AddTicks(5056),
                            UserId = 1
                        },
                        new
                        {
                            Id = 15,
                            CreatedDate = new DateTime(2023, 1, 12, 21, 57, 45, 855, DateTimeKind.Local).AddTicks(5058),
                            Description = "ÖSYM Yabancı Dil Sınavı (YDS) için seçilmiş kelimeler.",
                            IsDelete = false,
                            Title = "YDS İngilizce Kelimeleri",
                            UpdatedDate = new DateTime(2023, 1, 12, 21, 57, 45, 855, DateTimeKind.Local).AddTicks(5058),
                            UserId = 1
                        },
                        new
                        {
                            Id = 16,
                            CreatedDate = new DateTime(2023, 1, 12, 21, 57, 45, 855, DateTimeKind.Local).AddTicks(5060),
                            Description = "Günde 30 Kelime ile 1 Ayda 900 Kelime !",
                            IsDelete = false,
                            Title = "30 Days English Challange",
                            UpdatedDate = new DateTime(2023, 1, 12, 21, 57, 45, 855, DateTimeKind.Local).AddTicks(5061),
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Vocabulary.API.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 1, 12, 21, 57, 45, 855, DateTimeKind.Local).AddTicks(4778),
                            IsDelete = false,
                            Name = "Muhammet",
                            Surname = "Çağatay",
                            UpdatedDate = new DateTime(2023, 1, 12, 21, 57, 45, 855, DateTimeKind.Local).AddTicks(4779)
                        });
                });

            modelBuilder.Entity("Vocabulary.API.Models.Entities.Word", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CardId")
                        .HasColumnType("int");

                    b.Property<string>("Context")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.ToTable("Words");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CardId = 1,
                            Context = "Door",
                            CreatedDate = new DateTime(2023, 1, 12, 21, 57, 45, 855, DateTimeKind.Local).AddTicks(4885),
                            IsDelete = false,
                            UpdatedDate = new DateTime(2023, 1, 12, 21, 57, 45, 855, DateTimeKind.Local).AddTicks(4885)
                        },
                        new
                        {
                            Id = 2,
                            CardId = 1,
                            Context = "Window",
                            CreatedDate = new DateTime(2023, 1, 12, 21, 57, 45, 855, DateTimeKind.Local).AddTicks(4889),
                            IsDelete = false,
                            UpdatedDate = new DateTime(2023, 1, 12, 21, 57, 45, 855, DateTimeKind.Local).AddTicks(4890)
                        },
                        new
                        {
                            Id = 3,
                            CardId = 1,
                            Context = "Computer",
                            CreatedDate = new DateTime(2023, 1, 12, 21, 57, 45, 855, DateTimeKind.Local).AddTicks(4892),
                            IsDelete = false,
                            UpdatedDate = new DateTime(2023, 1, 12, 21, 57, 45, 855, DateTimeKind.Local).AddTicks(4892)
                        });
                });

            modelBuilder.Entity("Vocabulary.API.Models.Entities.WordAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTrue")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("WordId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WordId");

                    b.ToTable("WordAnswer", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Answer = "Kapı",
                            CreatedDate = new DateTime(2023, 1, 12, 21, 57, 45, 855, DateTimeKind.Local).AddTicks(4905),
                            IsDelete = false,
                            IsTrue = true,
                            UpdatedDate = new DateTime(2023, 1, 12, 21, 57, 45, 855, DateTimeKind.Local).AddTicks(4905),
                            WordId = 1
                        },
                        new
                        {
                            Id = 2,
                            Answer = "Kaldırım",
                            CreatedDate = new DateTime(2023, 1, 12, 21, 57, 45, 855, DateTimeKind.Local).AddTicks(4908),
                            IsDelete = false,
                            IsTrue = false,
                            UpdatedDate = new DateTime(2023, 1, 12, 21, 57, 45, 855, DateTimeKind.Local).AddTicks(4908),
                            WordId = 1
                        },
                        new
                        {
                            Id = 3,
                            Answer = "Uzay",
                            CreatedDate = new DateTime(2023, 1, 12, 21, 57, 45, 855, DateTimeKind.Local).AddTicks(4910),
                            IsDelete = false,
                            IsTrue = false,
                            UpdatedDate = new DateTime(2023, 1, 12, 21, 57, 45, 855, DateTimeKind.Local).AddTicks(4910),
                            WordId = 1
                        },
                        new
                        {
                            Id = 4,
                            Answer = "Şirket",
                            CreatedDate = new DateTime(2023, 1, 12, 21, 57, 45, 855, DateTimeKind.Local).AddTicks(4912),
                            IsDelete = false,
                            IsTrue = false,
                            UpdatedDate = new DateTime(2023, 1, 12, 21, 57, 45, 855, DateTimeKind.Local).AddTicks(4913),
                            WordId = 1
                        },
                        new
                        {
                            Id = 5,
                            Answer = "Pencere",
                            CreatedDate = new DateTime(2023, 1, 12, 21, 57, 45, 855, DateTimeKind.Local).AddTicks(4914),
                            IsDelete = false,
                            IsTrue = true,
                            UpdatedDate = new DateTime(2023, 1, 12, 21, 57, 45, 855, DateTimeKind.Local).AddTicks(4915),
                            WordId = 2
                        },
                        new
                        {
                            Id = 6,
                            Answer = "Limonata",
                            CreatedDate = new DateTime(2023, 1, 12, 21, 57, 45, 855, DateTimeKind.Local).AddTicks(4917),
                            IsDelete = false,
                            IsTrue = false,
                            UpdatedDate = new DateTime(2023, 1, 12, 21, 57, 45, 855, DateTimeKind.Local).AddTicks(4917),
                            WordId = 2
                        },
                        new
                        {
                            Id = 7,
                            Answer = "Sandalye",
                            CreatedDate = new DateTime(2023, 1, 12, 21, 57, 45, 855, DateTimeKind.Local).AddTicks(4918),
                            IsDelete = false,
                            IsTrue = false,
                            UpdatedDate = new DateTime(2023, 1, 12, 21, 57, 45, 855, DateTimeKind.Local).AddTicks(4919),
                            WordId = 2
                        },
                        new
                        {
                            Id = 8,
                            Answer = "Teknokent",
                            CreatedDate = new DateTime(2023, 1, 12, 21, 57, 45, 855, DateTimeKind.Local).AddTicks(4920),
                            IsDelete = false,
                            IsTrue = false,
                            UpdatedDate = new DateTime(2023, 1, 12, 21, 57, 45, 855, DateTimeKind.Local).AddTicks(4921),
                            WordId = 2
                        },
                        new
                        {
                            Id = 9,
                            Answer = "Bilgisayar",
                            CreatedDate = new DateTime(2023, 1, 12, 21, 57, 45, 855, DateTimeKind.Local).AddTicks(4923),
                            IsDelete = false,
                            IsTrue = true,
                            UpdatedDate = new DateTime(2023, 1, 12, 21, 57, 45, 855, DateTimeKind.Local).AddTicks(4923),
                            WordId = 3
                        },
                        new
                        {
                            Id = 10,
                            Answer = "Bardak",
                            CreatedDate = new DateTime(2023, 1, 12, 21, 57, 45, 855, DateTimeKind.Local).AddTicks(4924),
                            IsDelete = false,
                            IsTrue = false,
                            UpdatedDate = new DateTime(2023, 1, 12, 21, 57, 45, 855, DateTimeKind.Local).AddTicks(4925),
                            WordId = 3
                        },
                        new
                        {
                            Id = 11,
                            Answer = "Çanta",
                            CreatedDate = new DateTime(2023, 1, 12, 21, 57, 45, 855, DateTimeKind.Local).AddTicks(4926),
                            IsDelete = false,
                            IsTrue = false,
                            UpdatedDate = new DateTime(2023, 1, 12, 21, 57, 45, 855, DateTimeKind.Local).AddTicks(4927),
                            WordId = 3
                        },
                        new
                        {
                            Id = 12,
                            Answer = "Kalemlik",
                            CreatedDate = new DateTime(2023, 1, 12, 21, 57, 45, 855, DateTimeKind.Local).AddTicks(4928),
                            IsDelete = false,
                            IsTrue = false,
                            UpdatedDate = new DateTime(2023, 1, 12, 21, 57, 45, 855, DateTimeKind.Local).AddTicks(4929),
                            WordId = 3
                        });
                });

            modelBuilder.Entity("CourseUser", b =>
                {
                    b.HasOne("Vocabulary.API.Models.Entities.Course", null)
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("FK_CourseUsers_Courses");

                    b.HasOne("Vocabulary.API.Models.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_CourseUsers_Users");
                });

            modelBuilder.Entity("Vocabulary.API.Models.Entities.Card", b =>
                {
                    b.HasOne("Vocabulary.API.Models.Entities.Course", "Course")
                        .WithMany("Cards")
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("FK_Cards_Courses");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Vocabulary.API.Models.Entities.CardSession", b =>
                {
                    b.HasOne("Vocabulary.API.Models.Entities.Card", "Card")
                        .WithMany("CardSessions")
                        .HasForeignKey("CardId")
                        .IsRequired()
                        .HasConstraintName("FK_CardSession_Cards");

                    b.HasOne("Vocabulary.API.Models.Entities.User", "User")
                        .WithMany("CardSessions")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_CardSession_Users");

                    b.Navigation("Card");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Vocabulary.API.Models.Entities.Course", b =>
                {
                    b.HasOne("Vocabulary.API.Models.Entities.User", "User")
                        .WithMany("Courses")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Courses_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Vocabulary.API.Models.Entities.Word", b =>
                {
                    b.HasOne("Vocabulary.API.Models.Entities.Card", "Card")
                        .WithMany("Words")
                        .HasForeignKey("CardId")
                        .IsRequired()
                        .HasConstraintName("FK_Words_Cards");

                    b.Navigation("Card");
                });

            modelBuilder.Entity("Vocabulary.API.Models.Entities.WordAnswer", b =>
                {
                    b.HasOne("Vocabulary.API.Models.Entities.Word", "Word")
                        .WithMany("WordAnswers")
                        .HasForeignKey("WordId")
                        .IsRequired()
                        .HasConstraintName("FK_WordAnswer_Words");

                    b.Navigation("Word");
                });

            modelBuilder.Entity("Vocabulary.API.Models.Entities.Card", b =>
                {
                    b.Navigation("CardSessions");

                    b.Navigation("Words");
                });

            modelBuilder.Entity("Vocabulary.API.Models.Entities.Course", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("Vocabulary.API.Models.Entities.User", b =>
                {
                    b.Navigation("CardSessions");

                    b.Navigation("Courses");
                });

            modelBuilder.Entity("Vocabulary.API.Models.Entities.Word", b =>
                {
                    b.Navigation("WordAnswers");
                });
#pragma warning restore 612, 618
        }
    }
}
